package api.basic;

public class Util {
	/**
	 * Generate a pseudo-random int ranging from min to max (max excluded)
	 * 
	 * @param min The minimum value of the generated integer
	 * @param max The maximum value of the generated integer (not included)
	 * @return The pseudo-random integer generated by this method
	 */
	public static int random(int min, int max) {
		return (int) (Math.random() * (max - min));
	}
}
