echo off
echo Generating Javadoc...
javadoc -use -classpath "Hexapode Java API\lib\*" -sourcepath "Hexapode Java Api\src" --allow-script-in-comments -d docs -use -windowtitle "Hexapod Lynxmotion API Documentation" -header "Lynxmotion Hexapod Java API (unofficial API)" -overview "<h1>Lynxmotion Hexapod Java API</h1>This is the documentation of a Java API to control a Lynxmoation hexapod using Pi4J.<br>To start learning, we recommend reading the <a href="http://fablab-wiki.fsg-preetz.de/index.php?title=Hexapode_Lynxmotion_Roboter">wiki article (in German)</a> about this project or start playing around with the examples in the test-package right away." -J-Xmx512m -subpackages api test
echo Adding newly generated doc files...
git add -A docs
echo Committing...
git commit -a -m "Regenerated the Javadoc"
echo Pushing...
git push
echo Finished!
stop