echo off
echo Generating Javadoc...
javadoc -use -classpath "HexapodeJavaApi\lib\*";"HexapodeJavaApi\lib\thirdparty\*" -sourcepath "HexapodeJavaApi\src" --allow-script-in-comments -d docs -use -windowtitle "Hexapod Lynxmotion API Documentation" -header "Lynxmotion Hexapod Java API (unofficial API)" -doctitle "Lynxmotion Hexapod Java API" -overview "HexapodeJavaApi\src\overview.html" -J-Xmx512m -subpackages api:dev:test
pause
echo Adding newly generated doc files...
git add -A docs
echo Committing...
git commit -a -m "Regenerated the Javadoc"
echo Pushing...
git push
echo Finished!
pause
